title: Julia Mazzola
logo: assets/husky-modified.png
description: I am a recent graduate of the University of Connecticut, where I earned a Bachelor of Science in Economics and Statistical Data Science with a concentration in Financial Analysis. Starting this summer I will be returning to the Cigna Group as a Risk & Underwriting Senior Analyst through their Pharmacy Underwriting Development Program. I look forward to growing my expertise in healthcare analytics and contributing to data-informed innovation in the industry.
theme: jekyll-theme-minimal

