title: Julia Mazzola
#logo: INSERT HEADSHOT
description: I am currently a senior at the University of Connecticut pursuing a double major in Economics and Statistical Data Science with a domain in Financial Analysis. I graduate May 2025 and live in the New York City Metropolitan Area. I am passionate about combining my knowledge of economics and data science to build a career that uses data-driven insights to tackle complex economic and financial challenges.
theme: jekyll-theme-minimal
