title: Julia Mazzola
logo: assets/husky-modified.png
description: I am a senior at the University of Connecticut, double majoring in Economics and Statistical Data Science with a focus on Financial Analysis. I will be graduating in May 2025 and currently reside in the New York City Metropolitan Area. I am currently working on my Capstone Project, which integrates concepts from both fields to analyze real-world economic and financial topics, using data science methodologies and approaches.
theme: jekyll-theme-minimal

