title: Julia Mazzola
#logo: INSERT HEADSHOT
description: I am currently a senior at the University of Connecticut pursuing a double major in Economics and Statistical Data Science with a domain in Financial Analysis. I graduate May 2025 and live in the New York City Metropolitan Area.
theme: jekyll-theme-minimal
